config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/show'
  get 'pages/new'
  resources :pages
  resources :users
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    puts "in index method"
    @pages = Page.all # controller interacting with model

    # although we don't code anything, rails automatically grabs this for us
    # rails is going to look for index.html.erb in the views/pages folder
  end

  def show
      # find a page, but we need id
      @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
    # go to folder views/pages/new.html/txt/etc ex
  end

  def create
    @page = Page.new(pages_params)
    # new doesnt write new object to database, whereas create will
    if @page.save
      redirect_to pages_path
    else
      render :new
    end
  end

  def edit
    @page = Page.find(params[:id])

  end

  def update
    @page = Page.find(params[:id])

    if(@page.update(pages_params))
      redirect_to pages_path
    else
      render :edit
    end
  end

  private
  def pages_params
    params.require(:page).permit(:title, :author, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<h1>Pages</h1>
<%= link_to "new page", new_page_path %>
<% @pages.each do |page| %>
  <h2><%= page.title%></h2>
<%= link_to 'Show Page', page_path(page) %>
<%= link_to 'Edit Page', edit_page_path(page) %>
<% end %>

app/views/pages/new.html.erb
<h1>Create Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<h4><%= @page.author %></h4>
<p><%= @page.body %></p>
<%= link_to 'Back', pages_path %>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user|%>
  <h1><%= user.name %></h1>
  
<% end %>